version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
python:
  # Install our python package before building the docs
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/source/conf.py
  fail_on_warning: true
formats:
  - pdf
  - epub
